language: objective-c

before_install:
    - gem update --system
    - gem install ios_ci
    - gem install cocoapods
    - brew install ios-sim
script:
  	- make clean test
notifications:
  email:
    - korotan1@mac.com